[language-server.biome]
command = "biome"
args = ["lsp-proxy"]

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

[[language]]
name = "html"

[[language]]
name = "css"
formatter = { command = "biome", args = ["format", "--stdin-file-path", "a.css"]}
auto-format = true

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
formatter = { command = "biome", args = ["check", "--formatter-enabled", "true",  "--linter-enabled", "true", "--write", "--stdin-file-path", "%{buffer_name}"]}
auto-format = true

[[language]]
name = "tsx"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
formatter = { command = "biome", args = ["check", "--formatter-enabled", "true",  "--linter-enabled", "true", "--write", "--stdin-file-path", "%{buffer_name}"]}
auto-format = true

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]
formatter = { command = "biome", args = ["format", "--stdin-file-path", "a.json"] }
auto-format = true

[[language]]
name = "graphql"
formatter = { command = "biome", args = ["format", "--stdin-file-path", "a.graphql"] }
auto-format = true
